// ignore_for_file: public_member_api_docs, sort_constructors_first
/// Base class for all client-side errors that can be generated by the app
class AppException implements Exception {
  AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}
