name: Test App
on: [push, pull_request, workflow_dispatch]
jobs:
  drive:
    runs-on: macos-latest
    steps:
    - name: Flutter Checkout@v3
      uses: actions/checkout@v3
    - name: Use Flutter-action@v2.10.
      uses: subosito/flutter-action@v2.10.0
    - name: Run Flutter Test via Bash script
      run:  |
          chmod +x ./ecommerce_app/flutter_tests.sh
          ./ecommerce_app/flutter_tests.sh
   
